---
- hosts: localhost
  vars:
    vm_ip: "{{ip}}"
    xrdp_port: "{{ (vm_ip | int) + 7000}}"
    usbip_port: "{{ (vm_ip | int) + 6000}}"
  tasks:

  - name: Install autossh
    become: true
    apt:
      name: autossh
      state: present

  - name: Update ssh tunnel service file
    become: true
    lineinfile:
      name: /etc/rc.local
      state: present
      insertbefore: 'exit 0'
      line: sleep 60 &&  /usr/bin/autossh -oStrictHostKeyChecking=no -i /usr/local/bin/ACG-USBIP-pi/id_rsa -T -f -N  tunnel@204.197.1.140 -R {{xrdp_port}}:localhost:3389 &
  - name: Update usbip tunnel service file
    become: true
    lineinfile:
      name: /etc/rc.local
      state: present
      insertbefore: 'exit 0'
      line: sleep 60 && /usr/bin/autossh -oStrictHostKeyChecking=no -i /usr/local/bin/ACG-USBIP-pi/id_rsa -T -f -N  tunnel@204.197.1.140 -R {{usbip_port}}:localhost:3240 &
